name: Python Code Quality Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install ruff black pytest

      - name: Lint with ruff
        run: ruff check . --fix

      - name: Format code with black
        run: black .
      
      # ⬇️⬇️ هذه هي الخطوة الجديدة والمهمة لحل مشكلة المزامنة ⬇️⬇️
      - name: Pull changes to avoid conflicts
        run: git pull

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "style: Auto-format code with black and ruff"
          branch: ${{ github.head_ref || github.ref_name }}

      - name: Run tests with pytest
        run: pytest
