name: Python Code Quality Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        # ✅ تعديل: إضافة إعدادات لسحب كامل تاريخ الفرع وهو أفضل لعمليات git
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install ruff black pytest

      # ✅ تعديل: سحب التغييرات أصبح الخطوة الأولى بعد الإعداد
      - name: Synchronize with remote branch
        run: git pull --rebase
        # استخدام --rebase أفضل من merge commit في الـ workflows

      - name: Run tests before formatting
        run: pytest

      - name: Lint with ruff
        run: ruff check . --fix

      - name: Format code with black
        run: black .

      - name: Commit formatting changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "style: Auto-format code with black and ruff"
          branch: ${{ github.head_ref || github.ref_name }}
