name: Scrape Latest CBE Data

on:
  workflow_dispatch:
  schedule:
    # القاعدة 1: التشغيل كل ساعة من 5 مساءً إلى 11 مساءً بتوقيت مصر يومي الأحد والإثنين
    - cron: '0 14-20 * * 0,1'
    
    # القاعدة 2: التشغيل مرة واحدة الساعة 8 صباحًا بتوقيت مصر في باقي الأيام
    - cron: '0 5 * * 2-6'
    
    # القاعدة 3 (المعدلة): التشغيل مرة واحدة الساعة 12:10 صباحًا بتوقيت مصر
    - cron: '10 21 * * *'

jobs:
  scrape:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run scraper
        run: python scraper.py

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update CBE historical data [BOT]"
          file_pattern: cbe_historical_data.db
