name: Scrape Latest CBE Data

on:
  workflow_dispatch:
  schedule:
    # Rule 1: Run every hour from 14:00 to 20:00 UTC (5 PM to 11 PM Egypt Time) on Sunday and Monday.
    - cron: '0 14-20 * * 0,1'
    
    # Rule 2: Run once at 5:00 AM UTC (8 AM Egypt Time) on all other days (Tue-Sat).
    - cron: '0 5 * * 2-6'

jobs:
  scrape:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run scraper
        run: python scraper.py

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update CBE historical data [BOT]"
          file_pattern: cbe_historical_data.db
