name: Scrape Latest CBE Data

on:
  workflow_dispatch: # يسمح بالتشغيل اليدوي
  schedule:
    # يعمل يوميًا الساعة 5 صباحًا بتوقيت UTC (حوالي 8 صباحًا بتوقيت مصر)
    - cron: '0 5 * * *' 

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper
        run: python scraper.py

      - name: Commit and push if there are changes
        run: |
          git config --global user.name "CBE Data Scraper Bot"
          git config --global user.email "actions@github.com"
          git add cbe_historical_data.db || exit 0
          git diff --staged --quiet || (git commit -m "Update CBE historical data" && git push)
