name: Scrape Latest CBE Data

on:
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * *'

jobs:
  scrape:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run scraper
        run: python scraper.py

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update CBE historical data [BOT]"
          file_pattern: cbe_historical_data.db

      # --- الخطوة الجديدة والمهمة ---
      - name: Upload Page Source Artifact on Failure
        # هذه الخطوة ستعمل فقط في حالة فشل الخطوات السابقة
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: failed-page-source
          path: error_page.html
